manifest = "8b983235525a67f7b6552cd934a6b91ddc7d85978bed07b93112e64acaafaaac"

[[dependency]]
package = "github.com/buckaroo-pm/check"
target = "//:check"

[lock."github.com/buckaroo-pm/check"]
versions = [ "branch=master" ]
revision = "53e84bd2ed5d98cf98cb91e781a2983d7d01425d"
